version: '2'

services:
    nginx-data:
        container_name: nginx-data
        build: nginx-data
        volumes:
            - nginx-certs:/etc/nginx/certs
            - ./nginx-data:/etc/docker-gen/templates

    nginx:
        image: nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx-conf:/etc/nginx/conf.d
            - ./nginx-vhost:/etc/nginx/vhost.d
            - nginx-static:/usr/share/nginx/html
        volumes_from:
            - nginx-data
        networks:
            - proxy-tier
              ##logging:
              ##  driver: gelf
              ##  options:
              ##    gelf-address: "udp://127.0.0.1:12401"
              ##    tag: "nginx-proxy"

    nginx-gen:
        image: jwilder/docker-gen
        container_name: nginx-gen
        restart: always
        command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes_from:
            - nginx
            - nginx-data
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - proxy-tier

    nginx-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-letsencrypt
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        volumes_from:
            - nginx
            - nginx-data
        environment:
            - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
            - NGINX_PROXY_CONTAINER=nginx
        networks:
            - proxy-tier

volumes:
  nginx-certs:
  nginx-static:
    external: true

networks:
    proxy-tier:
        external:
            name: nginx-proxy
